apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-k8s-app
  template:
    metadata:
      labels:
        app: nodejs-k8s-app
    spec:
      containers:
        - name: nodejs-k8s-app
          image: timmo311/nodejs-k8s-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-k8s-service
spec:
  selector:
    app: nodejs-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
