image:
  repository: timmo311/nodejs-k8s-app
  tag: latest

service:
  port: 80

serviceAccount:
  create: true

ingress:
  enabled: true
  annotations: {}
  path: /

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
