apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-k8s-app
  template:
    metadata:
      labels:
        app: nodejs-k8s-app
    spec:
      containers:
        - name: nodejs-k8s-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
