apiVersion: v1
kind: Service
metadata:
  name: nodejs-k8s-service
spec:
  selector:
    app: nodejs-k8s-app
  ports:
    - protocol: TCP
      port: { { .Values.service.port } }
      targetPort: 3000
  type: NodePort
