name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/nodejs-k8s-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
        env:
          IMAGE_TAG: ${{ github.sha }}

  deploy_to_k8s:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO_URL }}
          token: ${{ secrets.REPO_TOKEN }}
          ref: main

      - name: Update deployment YAML
        run: |
          sed -i 's|image:.*|image: '"${{ secrets.DOCKER_USERNAME }}/nodejs-k8s-app:${{ github.sha }}"'|' k8s/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ secrets.DOCKER_USERNAME }}/nodejs-k8s-app:${{ github.sha }}"
          git push

  sync_argocd:
    runs-on: ubuntu-latest
    needs: deploy_to_k8s

    steps:
      - name: Sync ArgoCD Application
        run: |
          argocd app sync nodejs-k8s-app
